### ISSUE TITLE
Only Twitter IDs with country tags

### ISSUE THREAD

**Issue by JanPfleging** [UBC-NLP/megacov#1]
Hi,

I really appreciate your work - thanks for publishing it!
However, I have a question:
For an university project, we need twitter IDs with country tags. I started hydrating your twitter IDs, but it is nearly impossible to hydrate all of it in a appropriate time period and filter it afterwards.
Is it possible to publish an additional list of twitter IDs only that contain country tags, since we only need those? I think hydrating this shorter list would be possible. 

Thank you and best regards 
Jan

**Comment by mageed** [comment]
Thanks Jan. We have now published an updated version with country tags, and also broken data by year (and, for 2020, by months). We hope you'll find it useful and appreciate your interest in the work.
